/**:
  ros__parameters:
    map_frame: map
    utm_zone: 52
    origin_easting_m: 330316.75997010944
    origin_northing_m: 4156620.721868811
    origin_altitude_m: 0.0
    origin_source_csv: rosbag2_2026_03_30.csv
    min_position_variance_m2: 0.0001
