complex_target_node:
  ros__parameters:
    csv_path_topic: "/csv_path"
    target_topic: "/complex/rrt_target"
    target_marker_topic: "/complex/rrt_target_marker"
    roi_path_topic: "/complex/target_roi_path"
    target_frame: "vehicle_ref"
    csv_frame: "csv"
    timer_frequency: 20.0
    target_distance_m: 6.0
    search_span_points: 2000
    min_forward_x: 0.2
    max_target_abs_y: 6.0
    line_width: 0.18
