ublox_gps_node:
  ros__parameters:
    debug: 1
    device: /dev/ttyACM0
    frame_id: leader/leader_gps
    rate: 15.0
    nav_rate: 1
    dynamic_model: portable
    uart1:
      baudrate: 115200
    gnss:
      glonass: false
      beidou: false
      gps: true
      qzss: true
      galileo: true
      imes: false
      qzss_sig_cfg: 1114112
    tmode3: 0
    sv_in:
      reset: false
      min_dur: 300
      acc_lim: 3.0
    inf:
      all: true
    publish:
      aid/all: false
      rxm:
        rtcm: true
